const {randomUUID}=require('node:crypto');
function setup(db){db.exec(`CREATE TABLE IF NOT EXISTS account_preferences(user_id TEXT PRIMARY KEY REFERENCES users(id),payload TEXT NOT NULL);CREATE TABLE IF NOT EXISTS profiles(user_id TEXT PRIMARY KEY REFERENCES users(id),name TEXT NOT NULL DEFAULT '',locale TEXT NOT NULL DEFAULT '');CREATE TABLE IF NOT EXISTS tickets(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),subject TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS ticket_messages(id TEXT PRIMARY KEY,ticket_id TEXT NOT NULL REFERENCES tickets(id),sender TEXT NOT NULL,body TEXT NOT NULL,created INTEGER NOT NULL);`);}
const text=(v,max)=>typeof v==='string'&&v.trim().length>0&&v.length<=max;
function handle({req,res,url,data,db,user,reply}){if(!url.pathname.startsWith('/api/account/'))return false;if(!user){reply(res,401,{error:'authentication_required'});return true;}const route=url.pathname;
if(route==='/api/account/preferences'){if(req.method==='GET'){const row=db.prepare('SELECT payload FROM account_preferences WHERE user_id=?').get(user);reply(res,200,row?JSON.parse(row.payload):{});return true;}if(req.method==='POST'){const allowed={bio:500,experience:40,playStyle:40,availability:100};const value={};for(const [key,max] of Object.entries(allowed)){if(typeof data[key]!=='string'||data[key].length>max){reply(res,400,{error:'invalid_preferences'});return true;}value[key]=data[key].trim();}db.prepare('INSERT INTO account_preferences VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET payload=excluded.payload').run(user,JSON.stringify(value));reply(res,200,{ok:true});return true;}}
if(route==='/api/account/ticket-status'&&req.method==='POST'){if(!['open','closed'].includes(data.status)){reply(res,400,{error:'invalid_status'});return true;}const t=db.prepare('SELECT id FROM tickets WHERE id=? AND user_id=?').get(String(data.id),user);if(!t){reply(res,404,{error:'not_found'});return true;}if(data.status==='open'&&db.prepare("SELECT count(*) n FROM tickets WHERE user_id=? AND status='open'").get(user).n>=20){reply(res,429,{error:'ticket_limit'});return true;}db.prepare('UPDATE tickets SET status=? WHERE id=?').run(data.status,t.id);reply(res,200,{ok:true});return true;}
if(route==='/api/account/profile'){if(req.method==='GET'){reply(res,200,db.prepare('SELECT name,locale FROM profiles WHERE user_id=?').get(user)||{name:'',locale:''});return true;}if(req.method==='POST'){if(!text(data.name,100)||typeof data.locale!=='string'||data.locale.length>100){reply(res,400,{error:'invalid_profile'});return true;}db.prepare('INSERT INTO profiles VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,locale=excluded.locale').run(user,data.name.trim(),data.locale.trim());reply(res,200,{ok:true});return true;}}
if(route==='/api/account/tickets'){if(req.method==='GET'){const tickets=db.prepare('SELECT id,subject,status,created FROM tickets WHERE user_id=? ORDER BY created DESC LIMIT 100').all(user);for(const t of tickets)t.messages=db.prepare('SELECT sender,body,created FROM ticket_messages WHERE ticket_id=? ORDER BY created,id').all(t.id);reply(res,200,{tickets});return true;}if(req.method==='POST'){if(!text(data.subject,160)||!text(data.message,4000)){reply(res,400,{error:'invalid_ticket'});return true;}if(db.prepare("SELECT count(*) n FROM tickets WHERE user_id=? AND status='open'").get(user).n>=20){reply(res,429,{error:'ticket_limit'});return true;}const id=randomUUID();db.exec('BEGIN');try{db.prepare('INSERT INTO tickets VALUES(?,?,?,?,?)').run(id,user,data.subject.trim(),'open',Date.now());db.prepare('INSERT INTO ticket_messages VALUES(?,?,?,?,?)').run(randomUUID(),id,'customer',data.message.trim(),Date.now());db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}reply(res,201,{id});return true;}}
if(route==='/api/account/reply'&&req.method==='POST'){const t=typeof data.id==='string'&&db.prepare('SELECT * FROM tickets WHERE id=? AND user_id=?').get(data.id,user);if(!t){reply(res,404,{error:'not_found'});return true;}if(t.status!=='open'||!text(data.message,4000)){reply(res,400,{error:'invalid_message'});return true;}db.prepare('INSERT INTO ticket_messages VALUES(?,?,?,?,?)').run(randomUUID(),t.id,'customer',data.message.trim(),Date.now());reply(res,201,{ok:true});return true;}reply(res,404,{error:'not_found'});return true;}
module.exports={setup,handle};
