"""Continuations keep five existing kits, adding a second board and a closing act."""
def expand(kits, section, npc):
    additions = [
      dict(image='ponte-final',name='Amieiro — enfermaria e celeiro',places=[('Enfermaria',25,45),('Celeiro e comporta',76,46)],
        transition='Depois de sair do moinho e resolver a peça da carroça, a trilha leva a Amieiro. Mesmo se perderam a carroça ou tomaram a trilha norte, os viajantes chegam vivos; ajuste a chegada para o dia seguinte. Alina vê água entrando na enfermaria. Os remédios foram resgatados, mas ainda precisam chegar a quem os espera.',
        scenes=[section('5 · Enfermaria de Amieiro — 25 minutos','Mapa 2, área 1. Leia: “O sino da vila toca devagar. Pessoas levantam camas, enquanto uma curandeira aponta para o celeiro seco do outro lado da rua.”',
          'Objetivo: levar os seis passageiros e as três caixas à enfermaria provisória no celeiro. Entregue a pista 4. Separe dois trabalhos: transportar quem precisa de ajuda e proteger a carga. Cada personagem escolhe onde agir; descreva o resultado antes de pedir qualquer teste.',
          'Com Téo e a carroça, o transporte é automático em dez minutos. A pé, dois personagens gastam suas ações para carregar uma caixa por vez; os demais escoltam passageiros. A água rasa é terreno difícil, não exige teste para simplesmente andar.',
          'Uma prateleira cede: Força ND 10 segura as caixas ou Destreza ND 10 as recolhe. Falha molha apenas a embalagem e custa dez minutos para secar e conferir; os remédios continuam utilizáveis. Se Dário foi contratado, sua equipe segura a prateleira e dispensa esse teste.',
          'A curandeira entrega a pista 5 e aponta a comporta entupida. Passageiros seguros no celeiro permitem ao grupo cuidar dela sem reféns ou mortes automáticas.'),
          section('6 · Comporta do celeiro — 35 minutos','Mapa 2, área 2. Leia: “Um galho prende a roda da comporta. Atrás dela, a água procura saída; o caminho para os campos ainda está livre.”',
          'Objetivo: escoar a água para o canal vazio, preservando os mantimentos. Não há combate. Uma ação e Força ND 13 retiram o galho; depois uma ação e Destreza ND 10 prendem a roda com corda. Falha desloca quem tenta um quadrado para trás, causa 1 ponto de dano e permite nova abordagem.',
          'Alternativa sem teste: três personagens, ou dois e um morador, usam três ações coordenadas para sustentar, limpar e prender. Os materiais estão ao lado da comporta. Outra saída é uma barreira de sacos: leva vinte minutos e salva o celeiro, mas os campos permanecerão alagados por uma semana.',
          'Use três marcas locais de água; avance só em falhas ou a cada dez minutos de hesitação. Na terceira, parte dos grãos se perde, nunca os remédios já guardados. Retirar os sacos para a parte alta encerra a ameaça mesmo sem reparar a comporta.',
          'Encerramento: pergunte quem entrega os remédios e quem responde à gratidão dos passageiros. A curandeira reconhece as escolhas sobre Dário e o cavalo. Conceda a recompensa original uma única vez após esta cena; a perda de grãos altera a festa, não cancela o reconhecimento pelo resgate.')],
        handouts=[('Aviso da enfermaria','Levar passageiros e remédios ao celeiro alto. As embalagens podem ser secas; mantenham os frascos fechados.','Ao chegar a Amieiro, cena 5.'),('Desenho da comporta','O canal dos campos está vazio. Retirem o galho, abram a roda e prendam com uma corda. Sacos na porta protegem o celeiro enquanto trabalham.','Quando os passageiros estiverem seguros, cena 5.')],
        npc=npc('Celina','Curandeira de Amieiro','Organiza o abrigo e entrega instruções sem exigir testes.','Vida 8; Defesa 10; movimento 6 m; Medicina +3; usa Ajudar, não participa de ataques.')),
      dict(image='forja-final',name='Reservatório da oficina',places=[('Galeria de manutenção',24,47),('Câmara de alívio',74,47)],
        transition='Com Ivo fora de perigo e o protocolo da oficina resolvido, o sino emite uma nota contínua. A água parou de entrar na forja, mas ficou represada no reservatório antigo. Brina abre a galeria lateral; o resgate foi bem-sucedido e agora o grupo pode evitar perder a oficina.',
        scenes=[section('5 · Galeria de manutenção — 25 minutos','Mapa 2, área 1. Leia: “Três tubos vibram sobre o carrinho de ferramentas. Ivo reconhece a peça que instalou: ela cabe no encaixe, mas tampa a passagem lateral.”',
          'Entregue a pista 4. A válvula curta do carrinho é a peça correta; o desenho a identifica, sem exigir teste. Sabedoria ND 13 explica como isolar o tubo antes da troca. Falha provoca um jato de água fria que custa uma marca de pressão, sem dano.',
          'Uma pessoa mantém a alavanca de isolamento usando uma ação por rodada; outra usa uma ação e Destreza ND 13 para trocar a peça. Falha permite repetir e avança a pressão. Duas pessoas com ferramentas podem fazer a troca sem teste em três rodadas, mantendo a alavanca.',
          'Se Ivo foi levado para fora, Brina lê o desenho em seu lugar. Se o guardião foi destruído, o braço mecânico não ajuda, mas as ferramentas manuais continuam suficientes. Não anule escolhas do primeiro ato.',
          'A peça nova estabiliza os tubos e revela a pista 5 na placa da câmara seguinte. Trocar a peça não esvazia sozinho o reservatório.'),
          section('6 · Câmara de alívio — 35 minutos','Mapa 2, área 2. Leia: “Uma passarela contorna a água. Na porta de saída, uma roda tem duas posições: canal da mina e tanque de reserva.”',
          'O canal da mina está ocupado por trabalhadores; Brina informa isso sem teste. O tanque de reserva está vazio. A pista 5 mostra como direcionar o alívio para o tanque. Com essa informação, girar a roda custa duas ações e dispensa teste.',
          'Uma trava empenada prende a última volta: Força ND 13 ou Destreza ND 13 com ferramenta. Falha causa 1d4 de dano por esforço ou impacto e avança a pressão. Duas pessoas usando uma ação cada com uma barra de apoio resolvem sem teste.',
          'Pressão local: quatro marcas, uma por falha indicada. Na quarta, um cano rompe e alaga a passarela, tornando-a terreno difícil. Todos ainda podem sair pela galeria; fechar a oficina pela alavanca de emergência termina a ameaça, mas exige semanas de reparo. Não reinicie o relógio de inundação do primeiro mapa.',
          'Final: alívio para o tanque salva água e oficina. Fechamento de emergência salva todos, mas adia a produção. Brina reconhece Ivo por assumir o erro; os jogadores decidem se propõem treinamento ou afastamento. A recompensa original só é entregue agora e não se duplica.')],
        handouts=[('Ficha da válvula','Modelo curto: permite retorno lateral. Antes da troca, segurar a alavanca de isolamento. Ferramentas e peça de reserva no carrinho.','Galeria, cena 5.'),('Placa de alívio','Tanque de reserva: vazio. Canal da mina: passagem de trabalhadores. Direcionar ao tanque, liberar a trava, abrir a roda por completo.','Após estabilizar os tubos, cena 5.')],
        npc=npc('Dora','Responsável pela mina','Conhece a ocupação dos canais e pede um aviso antes de qualquer descarga.','Vida 15; Defesa 12; movimento 6 m; testes de ofício +4; pode Ajudar com a barra.')),
      dict(image='oasis-final',name='Travessia e pátio das caravanas',places=[('Leito seco e travessia',25,47),('Pátio de partilha',75,47)],
        transition='Após resolver o vazamento e descobrir o destino dos barris, Samira propõe levar a água ao pátio protegido adiante. Se as caravanas partiram separadas, ela envia mensageiros e ambas aceitam uma última parada para abastecer. O grupo acompanha a carga recuperada ou apenas os barris que conseguiu salvar.',
        scenes=[section('5 · Travessia do leito seco — 25 minutos','Mapa 2, área 1. Leia: “Uma roda afunda na areia. Do outro lado do leito, as sombras do pátio prometem descanso. Luma pede que soltem os animais antes de puxar a carroça.”',
          'Entregue a pista 4. Soltar os animais é uma ação, sem teste. Use Força ND 13 para empurrar com uma prancha ou Sabedoria ND 13 para montar apoio com pedras. Falha custa tempo e derrama um único cantil, não toda a água.',
          'Alternativa sem teste: descarregar, atravessar os barris rolando sobre pranchas e remontar a carga leva vinte minutos. Cada personagem descreve uma função. Se Narek confessou, ele e os vigias trabalham; diminua esse tempo para dez minutos.',
          'Uma rajada levanta areia: o grupo pode parar cinco minutos sob uma lona, sem rolar dados. Atravessar durante a rajada exige Constituição ND 13; falha deixa o personagem Exausto até um descanso breve, conforme o Livro IV. Não exija o teste de quem esperou.',
          'No outro lado, entregue a pista 5. As duas caravanas concordam sobre quanto cada uma trouxe; a disputa é sobre quem assume a perda. Siga para o pátio, sem segundo encontro de combate obrigatório.'),
          section('6 · Pátio de partilha — 35 minutos','Mapa 2, área 2. Leia: “Dois recipientes vazios estão sobre a mesa. Samira coloca entre eles o livro de carga: ‘Precisamos de água para todos chegarem, não de um vencedor.’”',
          'Objetivo: garantir a reserva mínima de viagem de ambas as caravanas e registrar a restituição. A água presente sempre permite o mínimo; se o posto foi abandonado, ninguém terá sobra para vender. Apresente esses fatos claramente, sem conta escondida.',
          'Cada grupo quer uma garantia: Luma pede pesagem pública; os outros viajantes pedem prioridade para feridos; Narek pede escolta para responder pelo prejuízo sem sofrer agressão. Uma proposta que atenda aos três pontos dispensa teste.',
          'Carisma ND 13 persuade as caravanas a dividirem também ferramentas e guia. Falha mantém o acordo mínimo; não desfaz o abastecimento. Se o grupo recusar negociar, Samira faz a divisão mínima e cada caravana segue sozinha.',
          'Final: acordo amplo cria uma rota compartilhada e o grupo ganha as recompensas originais. Acordo mínimo preserva vidas e o posto, sem novo animal além do já prometido. Dê a cada personagem uma pergunta de epílogo: com quem viajará, que promessa fará ou o que aprendeu sobre confiança?')],
        handouts=[('Cuidado com a carga','Soltar os corredores antes de puxar. Descarregar se a roda afundar. Pranchas e lona seguem presas à carroça.','Na travessia, cena 5.'),('Livro de partilha','A reserva mínima de cada caravana vem primeiro. Sobras só serão contadas depois. Feridos viajam à sombra; perdas serão registradas para restituição.','Ao chegar ao pátio, cena 6.')],
        npc=npc('Ravi','Porta-voz dos viajantes','Aceita a divisão pública e quer que ninguém seja deixado sem água.','Vida 14; Defesa 11; movimento 6 m; testes sociais +3; não combate.')),
      dict(image='jardim-final',name='Riacho e santuário das raízes',places=[('Travessia do riacho',24,49),('Santuário da memória',75,48)],
        transition='Quando os espelhos silenciam, o riacho volta a correr e carrega uma pequena placa de cristal. Naia reconhece a marca do santuário que recebia os ecos. Se a máquina foi destruída, a placa está opaca, mas ainda pode guardar novas lembranças. Eren quer devolver o objeto e reparar o caminho que sua intervenção danificou.',
        scenes=[section('5 · Riacho das raízes — 25 minutos','Mapa 2, área 1. Leia: “A corrente passa por pedras claras. Uma árvore caída interrompe a trilha, mas sua copa formou uma passagem até a outra margem.”',
          'Naia entrega a pista 4. A placa não exige sintonização, magia nem sacrifício. Não peça memórias pessoais aos jogadores: toda lembrança narrada pode ser inventada para o personagem, ou substituída por uma simples promessa.',
          'Destreza ND 13 atravessa pela árvore e prende uma corda. Falha faz perder o equilíbrio, custa uma marca de crepúsculo e retorna à margem sem dano. Com a corda presa, todos atravessam sem teste. Outra opção é contornar o riacho, gastando vinte minutos e uma marca.',
          'Força ND 13 remove um galho que bloqueia o fluxo. Falha causa 1d4 de dano por arranhão, mas abre a passagem. Dois personagens com uma corda podem deslocá-lo usando uma ação cada, sem teste.',
          'Se Eren foi resgatado, ele carrega ferramentas e sugere o contorno; não faz o teste pelo grupo. Sem ele, Naia oferece a mesma informação. Ao atravessar, entregue a pista 5.'),
          section('6 · Santuário da memória — 35 minutos','Mapa 2, área 2. Leia: “Três pedestais cercam uma bacia cristalina. Nenhum pede sangue ou poder: nas bases estão gravadas as palavras acolher, recordar e devolver.”',
          'A solução é colocar a placa no pedestal acolher, narrar uma lembrança fictícia ou promessa em recordar, e abrir o pequeno canal em devolver. A pista explica a sequência; cada passo custa uma ação, sem teste. Não existe resposta emocional correta.',
          'Se errarem a ordem, a luz se apaga e podem recomeçar, avançando uma marca de crepúsculo. Sabedoria ND 13 percebe a sequência sem ler a pista; falha apenas indica que devem examinar as inscrições. A canaleta emperrada pode ser limpa em uma ação com a ferramenta de Naia, sem teste.',
          'Crepúsculo: três marcas locais. Na terceira, acende-se a lanterna fornecida por Naia e a caminhada de volta leva mais tempo; o ritual permanece possível. Não use monstros extras para alongar a sessão.',
          'Final: se o observatório sobreviveu, a placa devolve os ecos antigos ao bosque. Se foi desligado à força, surge apenas a nova lembrança ou promessa; o passado continua perdido, preservando a consequência. Naia agradece e entrega a recompensa original uma vez. Cada personagem escolhe uma palavra que o jardim lembrará.')],
        handouts=[('Mensagem de Naia','A placa guarda ecos, não almas. Pode receber uma lembrança inventada ou uma promessa. Devolvê-la ao santuário encerra o ciclo.','Saída do observatório, antes da cena 5.'),('Inscrição do santuário','Acolher a placa. Recordar uma história ou promessa. Devolver a corrente abrindo o canal. A ordem guia a luz; não há sacrifício.','Travessia concluída, cena 5.')],
        npc=npc('Silen','Cuidador do santuário','Oferece uma lanterna e respeita quem prefere fazer uma promessa em silêncio.','Vida 16; Defesa 11; movimento 6 m; conhecimento do bosque +4; não combate.')),
      dict(image='farol-final',name='Enseada de resgate',places=[('Navio no banco de areia',27,48),('Cais protegido',76,46)],
        transition='Depois de corrigir ou apagar o sinal, Lia conduz a embarcação à enseada. Se o navio foi avisado a tempo, ele entrou voluntariamente no banco de areia para aguardar a maré; se encalhou, o casco está avariado. Em ambos os casos todos estão vivos, mas passageiros e carga precisam chegar ao cais antes da próxima onda.',
        scenes=[section('5 · Convés do navio — 25 minutos','Mapa 2, área 1. Leia: “O navio repousa inclinado na areia. A capitã aponta para uma prancha de embarque: ‘Primeiro as pessoas. As caixas podem esperar.’”',
          'Entregue a pista 4. São seis passageiros, um deles precisa de apoio. Com o barco de Lia ou uma prancha presa por cordas, desembarcar todos dispensa teste e leva dez minutos. Dois personagens acompanham quem tem dificuldade, usando movimento pela metade.',
          'Se o casco foi avariado no primeiro mapa, uma caixa fica presa: Força ND 13 a libera ou Destreza ND 13 solta a amarra. Falha custa uma marca de onda. Deixar a caixa é sempre possível, sem prejudicar o resgate; ela contém mercadorias, não remédios nem pessoas.',
          'Se o sinal foi corrigido a tempo, o casco intacto permite recuperar a caixa sem teste. A capitã entrega a pista 5, agradecendo a diferença que a ação no farol fez. Otávio fica com Lia, sem precisar ser resgatado outra vez.',
          'Mira cumpre um acordo de evacuação feito no armazém e ajuda a levar cordas. Se o grupo a hostilizou, a capitã fornece o material: nenhuma escolha anterior bloqueia a continuação.'),
          section('6 · Cais protegido — 35 minutos','Mapa 2, área 2. Leia: “Uma lanterna indica a água tranquila entre duas pedras. O cais está perto, mas uma amarra solta bate contra a parede.”',
          'Objetivo: prender a prancha ou a embarcação, receber passageiros e encerrar o resgate. Uma ação e Destreza ND 13 fazem o nó sob pressão. Falha custa uma marca de onda, sem derrubar passageiros. Duas pessoas usando duas ações cada podem fazer o trabalho sem teste.',
          'Três marcas locais de onda; avance nas falhas indicadas ou ao insistir dez minutos em carga opcional. Na terceira, a caixa remanescente é levada, mas todos os passageiros que aguardam no convés continuam seguros até a próxima viagem. Lia faz quantas viagens forem necessárias; não mate pessoas por um teste isolado.',
          'A capitã confirma a lista da pista 4. Com todos presentes, encerre os testes. Se houver acusações sobre Mira, a guarda recolhe depoimentos no cais; não exija outro combate nem resolva julgamento durante esta sessão.',
          'Epílogo: peça aos jogadores uma cena curta na vila, mostrando quem recebeu ajuda e o que ficou para trás. Recompensas originais são entregues uma vez. Farol reparado mantém a costa segura; farol apagado requer uma equipe de reparo. O estado do navio e a perda de carga continuam os estabelecidos pelas escolhas anteriores.')],
        handouts=[('Lista de bordo','Seis passageiros aguardam desembarque. Uma pessoa precisa de apoio. Nenhuma caixa tem prioridade sobre vidas. Confirmar a chegada de todos no cais.','No navio, cena 5.'),('Rota da enseada','Manter a lanterna do cais entre as duas pedras. Prender a amarra antes de desembarcar. A caixa restante contém tecido e ferramentas de comércio.','Após organizar o desembarque, cena 5.')],
        npc=npc('Capitã Mara','Comandante do mercante','Abandona mercadoria para proteger a tripulação; confirma o efeito do sinal.','Vida 22; Defesa 13; movimento 6 m; navegação +5; usa Ajudar no resgate, não ataca.'))
    ]
    for k,a in zip(kits,additions):
        m=dict(name=a['name'],image='assets/img/kits/'+a['image']+'.webp',columns=30,rows=20,cellMeters=1.5,locations=[dict(id=str(i+1),name=n,x=x,y=y,secret=False) for i,(n,x,y) in enumerate(a['places'])],routes=[])
        k['maps']=[k['map'],m]
        k['duration']='One-shot de 4–5 horas para 3–5 jogadores; versão curta de 3 horas nas orientações.'
        k['preparation'][0]=k['preparation'][0].replace('Reserve 20 minutos','Reserve 15 minutos')
        k['preparation'][1]='Leia a verdade, as seis cenas e o desfecho. Combine um vínculo de cada personagem com a missão antes de começar.'
        k['preparation'].append('Dois mapas por kit. Mapa 1: cenas 1–4; mapa 2: cenas 5–6. Entregue as pistas 4 e 5 somente nos momentos indicados. Os dois mapas não são geograficamente contíguos: narre a transição entre eles.')
        k['gmSections'][0]['points'][0]='Duração completa: abertura 15 min; cenas 1–4 até 120 min; transição e descanso 15 min; cenas 5–6 até 60 min; epílogo 15 min. Reserve até 45 min extras se houver combate. Total previsto: 3h45–4h30, com margem até 5h.'
        end=k['gmSections'].pop()
        k['gmSections'] += [section('Passagem para o segundo cenário',a['transition'],
          'Encerre o relógio do mapa anterior; seus danos e consequências permanecem. Use apenas o relógio local indicado nas próximas cenas.',
          'Ofereça um descanso breve se o local estiver seguro, aplicando apenas a recuperação do Livro IV. Não restaure recursos automaticamente nem conceda nível no intervalo.',
          'Versão de 3 horas: após até 90 minutos no primeiro mapa, entregue informações essenciais e resolva a última negociação por acordo. Narre a cena 5 em dez minutos com sua alternativa sem teste; jogue a cena 6 por 30 minutos e reserve 15 para o epílogo. Combates são opcionais e nunca a única solução.')]+a['scenes']+[end]
        end['title']='Recompensas e encerramento do one-shot'
        end['text']='Aplique depois da cena 6, levando em conta as consequências dos dois mapas. '+end['text']
        end['points'].append('Conceda no máximo um marco de progressão por aventura completa, não um por mapa. Ganchos finais são convites opcionais: este one-shot termina com a resolução da missão e não exige outra sessão.')
        k['handouts'] += [dict(name=n,text=t,when=w) for n,t,w in a['handouts']]
        k['npcs'].append(a['npc'])
