"""Authoring source for the five session kits."""
import json
from pathlib import Path

def section(title, text, *points):
    return dict(title=title, text=text, points=list(points))

def npc(name, role, approach, combat):
    return dict(name=name, role=role, approach=approach, combat=combat)

def kit(slug, name, place, level, objective, opening, truth, image, locations, scenes, npcs, handouts, endings):
    return dict(id=slug,name=name,place=place,level=level,duration='Uma sessão de 3–4 horas; pode ser dividida em duas.',objective=objective,
        playerIntro=opening,
        map=dict(name=name+' — mapa tático',image='assets/img/kits/'+image+'.webp',columns=30,rows=20,cellMeters=1.5,
            locations=[dict(id=str(i+1),name=n,x=x,y=y,secret=False) for i,(n,x,y) in enumerate(locations)],routes=[]),
        preparation=['Grupo de 3–5 personagens; referência: 4 jogadores. '+level+'. Reserve 20 minutos para apresentar vínculos e regras.',
            'Leia a verdade e os desfechos. Escolha um vínculo: alguém depende da carga, conhece um morador ou deve um favor à pessoa que pede ajuda.',
            'Combine limites de conteúdo; qualquer pessoa pode pedir pausa. Aventura sem necessidade de tortura, crueldade com animais ou conflito entre jogadores.',
            'Separe os materiais dos jogadores. Entregue cada pista somente na cena indicada; não mostre a legenda do mestre antes da exploração.',
            'Use 30 × 20 quadrados, cada um com 1,5 m. Movimento de 6 m equivale a 4 quadrados; diagonais custam 1 quadrado, sem atravessar cantos de paredes. Paredes bloqueiam movimento; entulho e água rasa custam o dobro.'],
        gmSections=[section('Ficha rápida e verdade do mestre',truth,
            'Ritmo sugerido: abertura 20 min, investigação 50 min, complicação 40 min, clímax 50 min, epílogo 20 min. Se faltar tempo, entregue a pista essencial sem teste.',
            'Testes: 1d20 + atributo; ND 10 fácil, ND 13 moderado, ND 16 difícil. Perícia pertinente ou papel aplicável concede vantagem (2d20, fica o maior). Não acumule vantagens.',
            'Pistas essenciais não dependem de sucesso. Testes revelam atalhos ou reduzem custos. Uma falha muda a situação; não impede continuar.',
            'Estas fichas de adversários são próprias do kit. Ataque indica bônus total; dano já inclui bônus. Não some atributos outra vez. Um ataque ou outra ação por turno, movimento de 6 m salvo indicação.'),
            section('Leia na abertura',opening)]+scenes+[section('Desfechos, recompensa e próxima sessão',endings,
            'Cada personagem pode recuperar recursos com os descansos do Livro IV. Não restaure Vida ou Mana automaticamente entre cenas.',
            'Após resolver a ameaça central e encerrar os vínculos, este kit conta como um marco de campanha. O mestre pode conceder 1 nível a quem estava no nível inicial indicado; não conceda níveis por repetir o kit.',
            'Pergunte: quem você ajudou, o que mudou em seu personagem e qual promessa levará adiante? Registre relações, equipamentos e consequências na ficha.')],
        npcs=npcs,handouts=[dict(name=n,text=t,when=w) for n,t,w in handouts])

kits=[]
kits.append(kit('demo-ponte','A ponte esquecida','Estradas de Valmeira','Nível 1',
 'Resgatar uma caravana e decidir o futuro de uma travessia abandonada.',
 'Alina chega à estrada com a capa encharcada: “Meu irmão levava remédios para Amieiro. A caravana não voltou. A ponte antiga é o único caminho antes da cheia.” Ao longe, a roda de um moinho bate na água, embora o lugar esteja abandonado há anos.',
 'Uma cheia danificou o eixo de uma carroça. O condutor Téo abrigou os viajantes no moinho. Dário e dois cobradores tomaram o depósito e exigem uma taxa ilegal, mas também estão presos pela chuva. Ninguém desapareceu por magia; a urgência é a água e a carga de remédios.',
 'ponte',[('Acampamento',18,20),('Ponte',49,44),('Depósito',88,21),('Moinho',79,66)],
 [section('1 · Acampamento: quem ficou para trás?','Leia: “Tendas vazias resistem ao vento. Um cavalo relincha junto à carroça quebrada; pegadas seguem para a ponte.”',
    'Sem teste: as pegadas vão ao moinho; sob a lona há uma lista de carga (entregue a pista 1). Alina diz que Téo conhece reparos e não abandonaria os passageiros.',
    'Sabedoria ND 10 encontra corda e uma prancha firme: vantagem no primeiro teste de travessia ou reparo. Falha leva 10 minutos, mas ainda encontra a corda.',
    'O cavalo está assustado. Sabedoria ND 13 ou comida e 10 minutos o acalmam. Pode transportar a carga depois; não é prêmio automático. Siga para a ponte ou chame os viajantes da margem.'),
  section('2 · Ponte: atravessar sem perder a carga','Leia: “Duas lajes se moveram. A água passa logo abaixo delas. Do outro lado, alguém acena de uma janela.”',
    'A ponte é atravessável com cuidado, sem teste. Correr ou conduzir carroça exige Destreza ND 13. Falha: fica caído na ponte, sofre 1d4 e perde o movimento; não cai diretamente no rio.',
    'Reforçar com a prancha e corda custa uma ação e Força ou Sabedoria ND 13; ajuda de aliado concede vantagem. Falha consome tempo, permite nova tentativa com outra abordagem.',
    'Pelo rio: água rasa junto às margens é terreno difícil; a faixa central é profunda. Entrar exige Força ND 13 por travessia; falha leva 3 m rio abaixo e perde 1d4 de Vida, terminando numa pedra. Um aliado com corda pode puxar usando uma ação, sem novo teste.'),
  section('3 · Moinho: testemunhas e um acordo','Leia: “Seis viajantes dividem o chão com caixas de remédios. Téo segura uma roda quebrada. ‘Os cobradores levaram a ferramenta e a peça que falta.’”',
    'A pista 2 é dada por Téo sem teste. A peça fica no depósito. O grupo pode negociar, buscar outro eixo no acampamento ou recuperar a peça escondido.',
    'Téo oferece reparar a carroça em 20 minutos se trouxerem a peça. Sabedoria ND 13 adapta uma peça velha em 30 minutos; falha aumenta para 50 minutos. Os remédios podem ser levados a pé em duas viagens, sempre uma alternativa.',
    'Um passageiro ferido tem Vida 2/7, está consciente e não precisa de teste de morte. Medicina ND 10 o deixa apto a caminhar; falha permite levá-lo apoiado, com movimento do ajudante pela metade.'),
  section('4 · Depósito: a taxa de Dário','Leia: “Três figuras cercam uma lamparina. A ferramenta está sobre a mesa. ‘A ponte é nossa enquanto ninguém pagar pelo conserto’, diz Dário.”',
    'Dário aceita devolver a peça se o grupo prometer apresentar sua equipe à vila para trabalho legítimo ou ajudar a reforçar a ponte. Carisma ND 13 reduz a exigência a uma promessa simples; argumento concreto e prova da carga dispensam teste.',
    'Furtividade pertinente: Destreza ND 13 para pegar a ferramenta pela janela. Falha inicia conversa em posição desfavorável, não combate automático.',
    'Se houver combate, use Dário e 2 cobradores. Para 3 jogadores, apenas 1 cobrador; para 5, acrescente 1. Começam separados por 3 m. Cobradores rendem-se quando Dário cai ou quando dois adversários são derrotados. Dário oferece acordo a metade da Vida.'),
  section('Relógio da cheia · 4 marcas','Avance uma marca depois de cada cena ou de 20 minutos extras gastos; explique a mudança antes de avançar.',
    '1: a água sobe e a ponte range. 2: o acampamento fica enlameado, terreno difícil. 3: atravessar com carroça exige o reforço; a passagem a pé continua possível. 4: a carroça fica para trás, mas passageiros e remédios podem sair pela trilha norte, perdendo um dia de viagem.',
    'O relógio cria custo e escolha, nunca mata personagens fora de cena. Reforçar a ponte interrompe o relógio por uma cena.')],
 [npc('Alina','Mensageira e vínculo','Fala depressa, oferece informações e acompanha feridos. Quer Téo vivo.','Não combatente: Vida 7, Defesa 10, movimento 6 m; usa Defender ou Ajudar.'),
  npc('Téo','Condutor e mecânico','Quer salvar os passageiros antes das mercadorias. Oferece reparos e gratidão.','Não combatente: Vida 9, Defesa 11, movimento 6 m.'),
  npc('Dário','Cobrador desesperado','Não quer assassinatos; aceita trabalho e reconhecimento no lugar da taxa.','Vida 12; Defesa 11; ataque +3, bastão 1d6+1, alcance 1,5 m; movimento 6 m; testes relevantes +2.'),
  npc('Cobrador','Ajudante de Dário','Segue o líder, mas foge diante de risco de morte.','Vida 8; Defesa 10; ataque +2, porrete 1d4+1, alcance 1,5 m; movimento 6 m; testes +1.')],
 [('Lista de carga','Seis passageiros. Três caixas de remédios. Uma roda reserva. Destino: Amieiro. Condutor: Téo.','Cena 1, sob a lona.'),
  ('Recado de Téo','Estamos no moinho. A ferramenta e o encaixe estão com os homens do depósito. Não atravessem correndo.','Cena 3, entregue por Téo.'),
  ('Promessa da vila','Quem ajudar a devolver a carga terá abrigo, alimento e trabalho de reparo garantidos na chegada. — Alina','No acordo com Dário ou no epílogo.')],
 'Resgate completo: os viajantes chegam juntos e a vila oferece abrigo e alimentação por uma semana, além de corda e ferramenta para o grupo. Se a carroça for perdida, não há ferramenta de presente, mas os moradores reconhecem o resgate. Se Dário receber uma chance, torna-se contato de estrada; se expulso, a vila precisará de vigias. Téo pode emprestar o Cavalo de Valmeira a um personagem que cuidou dele, com compromisso de devolução após a próxima missão. Gancho: a lista de carga tem uma encomenda selada para uma oficina anã.'))

kits.append(kit('sino-pedra','O sino sob a pedra','Oficina nas montanhas anãs','Níveis 2–3',
 'Reabrir uma oficina alagada e descobrir por que seu guardião impede o resgate.',
 'A mestre de forja Brina aponta para a montanha: “O sino tocou três vezes e as portas fecharam. Meu aprendiz está lá dentro. Não quero heróis mortos; quero que voltem com ele.” Uma cabra enorme espera no estábulo com as rédeas ainda presas.',
 'O aprendiz Ivo trocou uma válvula rachada por uma peça de tamanho errado. O mecanismo de proteção selou a oficina. O guardião de bronze obedece ao protocolo de inundação, não é maligno. Ivo está isolado na sala de bombas. É possível salvar todos sem lutar.',
 'forja',[('Pátio e estábulo',17,43),('Forja',48,21),('Arquivo',49,74),('Sala de bombas',84,48)],
 [section('1 · Pátio: entrar com segurança','Leia: “O sino vibra dentro da pedra. A cabra recua a cada toque. No chão, uma corrente foi abandonada às pressas.”',
    'Brina entrega a chave da entrada e a pista 1. Não há teste para entrar. A cabra pode carregar ferramentas, mas não cabe no arquivo.',
    'Sabedoria ND 10 acalma a cabra e permite notar que os toques vêm da sala de bombas. Falha não bloqueia a pista: o animal aponta as orelhas naquela direção depois de alguns minutos.',
    'Retire uma corrente e duas cunhas do pátio. Servem para travar o guardião ou sustentar a válvula. O caminho leva à forja e ao arquivo, em qualquer ordem.'),
  section('2 · Forja: ferramenta e protocolo','Leia: “As brasas ainda brilham. Um braço de bronze se ergue: ‘Protocolo de cheia. Acesso à bomba interditado.’”',
    'O guardião não ataca quem fica no corredor. Uma identificação da oficina, encontrada no arquivo, permite aproximação. Carisma ND 13 faz o guardião aceitar uma inspeção acompanhada por dois turnos.',
    'Sem teste: a bancada tem uma válvula correta e a pista 2. A peça pesa o bastante para ocupar as duas mãos. Levar a peça remove a necessidade de improvisar na cena 4.',
    'Se os jogadores atacarem ou forçarem a porta, use 1 guardião e 1 sentinela. Para 3 jogadores, só guardião; para 5, mais 1 sentinela. Todos param se ouvirem a ordem completa do arquivo. A corrente pode imobilizar um construto: ação e Força ND 13; ele usa a próxima ação para escapar, automaticamente.'),
  section('3 · Arquivo: o erro humano','Leia: “Na mesa, um manual está aberto e molhado. Entre as páginas há um desenho feito por alguém com pressa.”',
    'Entregue a pista 3 sem teste. O protocolo escrito é completo: fechar a entrada de água, aliviar a pressão e só então trocar a válvula. Não exija que o jogador adivinhe palavras.',
    'Sabedoria ND 13 encontra um selo de manutenção: permite dar a ordem de desativação ao guardião sem teste. Falha encontra o selo, mas o relógio avança uma marca pelo tempo gasto.',
    'Ivo responde a batidas na tubulação e confirma estar consciente. O caminho de volta ao pátio permanece livre; retirada é possível.'),
  section('4 · Sala de bombas: três tarefas sob pressão','Leia: “Ivo se equilibra numa plataforma. A roda treme e a água alcança seus tornozelos.”',
    'Resolva em ordem: fechar a entrada (Força ND 13), aliviar a pressão (Sabedoria ND 10), instalar a peça correta (Destreza ND 13). Cada tarefa usa uma ação; Ajudar concede vantagem. Sucesso permanece registrado.',
    'Falha causa 1d4 de dano de vapor ao executor e avança uma marca, mas permite tentar novamente. Com cunhas e corrente, o primeiro passo dispensa teste. Após ler o manual, o segundo passo dispensa teste. Usar peça improvisada eleva o terceiro a ND 16.',
    'Alternativa: retirar Ivo com corda, uma ação e Força ND 10, abandonar a bomba e evacuar. Salva a vida, mas a oficina fecha por semanas. Não é necessário derrotar o guardião para vencer.'),
  section('Relógio da pressão · 5 marcas','Comece em 0. Avance ao terminar cada cena ou por falha na bomba, no máximo uma vez por rodada.',
    '2: água rasa na sala de bombas, terreno difícil. 3: vapor torna ataques à distância nessa sala desfavoráveis. 4: Brina abre uma rota de saída e chama pelo grupo. 5: a bomba desliga de emergência; todos podem sair pela rota, mas o equipamento é perdido. Nenhuma morte automática.',
    'Fechar a entrada de água impede avanços por passagem de tempo; falhas ainda aumentam a pressão residual até o alívio.')],
 [npc('Brina','Mestre de forja','Prática e protetora. Não esconde informações; quer pessoas antes do patrimônio.','Vida 15; Defesa 12; ajuda fora do combate, testes de ofício +4.'),
  npc('Ivo','Aprendiz','Admite o erro quando está seguro. Conhece o trajeto das tubulações.','Vida 7/9; Defesa 10; sem ataque; pode Ajudar depois de resgatado.'),
  npc('Guardião de bronze','Construto de proteção','Ordena recuo antes de atacar. Desliga pela ordem: “Manutenção, pressão segura, abrir passagem”.','Vida 22; Defesa 13; ataque +4, braço 1d6+2; movimento 4,5 m; testes +3. Não persegue fora da forja. Não tem resistência a dano.'),
  npc('Sentinela','Construto menor','Guarda a porta junto ao guardião.','Vida 10; Defesa 11; ataque +3, impacto 1d4+1; movimento 6 m; testes +2. Desliga com o guardião.')],
 [('Chave e aviso','Se o sino tocar três vezes, não force a roda. Procure o manual no arquivo e a peça marcada na bancada.','Cena 1, Brina.'),
  ('Etiqueta da válvula','Modelo B. Usar na linha azul. Fechar entrada antes de desmontar.','Cena 2, bancada.'),
  ('Manual de emergência','1. Feche a entrada. 2. Abra o alívio. 3. Troque a válvula. Ordem aos guardiões: Manutenção, pressão segura, abrir passagem.','Cena 3, mesa do arquivo.')],
 'Resgatar Ivo garante amizade da oficina e reparo gratuito de um equipamento comum por personagem. Salvar também a bomba rende uma Cabra das Alturas ao grupo, com sela e cuidados explicados por Brina. Se a oficina for perdida, Brina ainda agradece pelo aprendiz e pede ajuda para conseguir peças; não há prêmio de montaria. Se o guardião sobreviver, torna-se uma memória da solução pacífica. Gancho: a válvula defeituosa veio de uma caravana do Deserto Ardente.'))

kits.append(kit('agua-cinzas','Água entre as cinzas','Posto de passagem no Deserto Ardente','Níveis 3–4',
 'Salvar a reserva de água de um entreposto e impedir uma guerra entre duas caravanas.',
 'Duas caravanas param diante de um oásis. A água baixa diante de seus olhos. A zeladora Samira ergue as mãos: “Se começarmos a lutar, ninguém chegará à próxima cidade.” No curral, os corredores escamosos farejam a areia úmida.',
 'Uma fissura na cisterna está desviando a água para o depósito da torre. O mercador Narek descobriu a falha e guardou os barris intactos para revendê-los, espalhando a suspeita contra a outra caravana. Ele aceita devolver tudo se sua segurança for garantida; seus dois vigias não sabem toda a verdade.',
 'oasis',[('Caravanas e curral',17,52),('Oásis',47,55),('Cisterna',79,19),('Torre e depósito',80,72)],
 [section('1 · Caravanas: duas versões','Leia: “Sacos de ração viraram assentos. Todos falam ao mesmo tempo; ninguém olha para a rachadura úmida no chão.”',
    'Samira informa gratuitamente que o nível caiu durante a noite. Narek culpa os recém-chegados. A condutora Luma apresenta sua lista: os próprios barris também estão vazios (pista 1).',
    'Carisma ND 13 estabelece uma trégua até a investigação terminar. Falha exige deixar uma pessoa de confiança junto a Samira ou oferecer um barril de garantia; nenhuma condição bloqueia o acesso aos locais.',
    'Uma montaria fareja a trilha úmida que leva à cisterna. Sabedoria ND 10 a conduz com calma; falha exige conduzi-la pelas rédeas. Não force combate com o animal.'),
  section('2 · Oásis: seguir o caminho da água','Leia: “Bolhas surgem num canto do poço. A corrente puxa folhas para uma fenda sob as pedras.”',
    'Sem teste: há um vazamento, não veneno. A pista 2 mostra a ligação antiga com a torre. Observar por alguns minutos revela o sentido da água.',
    'Sabedoria ND 13 encontra um ponto seguro para bloquear a fissura com tecido e argila; sucesso atrasa o relógio em uma marca. Falha gasta o material sem piorar a água.',
    'Entrar na água custa movimento dobrado. A cisterna tem escadas; ninguém precisa mergulhar para achar a pista. Luma pode ficar cuidando das montarias.'),
  section('3 · Cisterna: fechar a fuga','Leia: “Uma comporta empenada deixa passar um fio constante. Marcas de mãos recentes cobrem a poeira.”',
    'A fissura se fecha com duas ações: Força ND 13 para alinhar a comporta, depois Destreza ou Sabedoria ND 13 para vedar. Corda, tecido e argila estão no posto, sem custo adicional. Falha avança o relógio, permite outro método; Ajudar concede vantagem.',
    'Entregue a pista 3: marcas de rodas seguem para a torre e o lacre pertence a Narek. Pode ser prova para negociar ou motivo para ir discretamente ao depósito.',
    'Alternativa: esvaziar a cisterna em barris e abandonar o posto. Leva duas cenas de trabalho e salva água suficiente para todos viajarem, mas o entreposto fecha.') ,
  section('4 · Torre: recuperar sem iniciar uma guerra','Leia: “Barricas intactas ocupam o depósito. Narek baixa a voz: ‘Eu só queria garantir a próxima viagem. Posso devolver.’”',
    'Apresentar lacre e trilha basta para Narek admitir. Carisma ND 13 obtém devolução e confissão pública; falha obtém devolução em troca de escolta segura. Os vigias aceitam a verdade e não precisam ser derrotados.',
    'Se atacado, Narek foge em vez de lutar. Use 2 vigias e 1 chefe; para 3 jogadores retire 1 vigia, para 5 acrescente 1. Barris dão +2 Defesa contra ataques à distância quando cobrem ao menos metade do alvo; não acumulam com outra cobertura.',
    'Vigias rendem-se quando o chefe cai ou quando a prova é apresentada usando uma ação e Carisma ND 13. Uma pessoa pode mover um barril com ação e movimento pela metade. Não incendie automaticamente barris de água.') ,
  section('Relógio de tensão · 5 marcas','Avance uma marca por cena e por falhas que dizem explicitamente para avançar; no máximo uma por rodada.',
    '2: as caravanas deixam de compartilhar provisões. 3: Samira pede decisão, o poço baixa visivelmente. 4: uma caravana se prepara para partir. 5: ambas partem em rotas separadas; o grupo ainda pode consertar o posto e levar provas, mas perde o acordo de cooperação.',
    'Uma confissão ou acordo de partilha encerra a tensão. Reparar a comporta detém o vazamento; são dois problemas distintos, que podem ser resolvidos em qualquer ordem.')],
 [npc('Samira','Zeladora do posto','Escuta ambos os lados e sabe onde estão as ferramentas.','Vida 13; Defesa 11; testes de ofício +3; prefere Ajudar.'),
  npc('Luma','Condutora de caravana','É franca e conhece seus corredores pelo nome. Quer uma travessia justa.','Vida 15; Defesa 12; testes com animais +4; não toma o protagonismo do grupo.'),
  npc('Narek','Mercador oportunista','Fala baixo, nega primeiro, aceita devolução com proteção.','Vida 10; Defesa 10; movimento 6 m; sem ataque; foge ou se rende.'),
  npc('Vigia','Protege o depósito','Acredita estar protegendo água comprada honestamente.','Vida 14; Defesa 12; ataque +4, lança 1d6+2, alcance 1,5 m; movimento 6 m; testes +2.'),
  npc('Chefe dos vigias','Responsável pela escolta','Não aceita ser usado como bode expiatório; escuta provas.','Vida 24; Defesa 13; ataque +5, espada 1d8+2, alcance 1,5 m; movimento 6 m; testes +3.')],
 [('Lista de Luma','Nossos barris chegaram lacrados. Perdemos água enquanto todos dormiam, junto aos barris da caravana rival.','Cena 1, condutora.'),
  ('Planta de manutenção','A cisterna antiga e o depósito da torre dividem um canal. Vedação: tecido, argila e pressão na comporta.','Cena 2, placa do posto.'),
  ('Lacre quebrado','O selo dos barris intactos é o mesmo usado nas mercadorias de Narek. Há marcas recentes de rodas entre cisterna e torre.','Cena 3, vestígio da carga.')],
 'Água e trégua salvas: o grupo ganha provisões para uma semana e um Corredor das Cinzas cedido por Luma, com sela, em reconhecimento ao cuidado com as caravanas. Água salva sem acordo: somente as provisões e o posto como abrigo. Caravanas dispersas: não há recompensa material, mas Samira mantém a amizade e pede ajuda para reunir os viajantes. Narek pode enfrentar restituição e serviço ao posto, sem execução obrigatória. Gancho: os viajantes encontram uma marca de oficina anã no mecanismo que rompeu; acidente ou negligência?'))

kits.append(kit('jardim-ecos','O jardim dos ecos','Santuário élfico esquecido','Níveis 4–5',
 'Reabrir um observatório e devolver ao bosque as memórias presas em seus espelhos.',
 'A guardiã Naia espera sob um arco coberto de flores: “O jardim repete nossas últimas palavras, mas ninguém ouve o riacho. Meu aprendiz entrou para consertar os espelhos e não voltou.” Uma luz prateada pulsa entre as árvores.',
 'O aprendiz Eren desviou água do jardim para mover os espelhos. A comporta travou e o observatório passou a guardar ecos de vozes. Eren está vivo, preso na biblioteca por raízes que respondem à máquina. Não há maldição nem necessidade de destruir o bosque. Libertar Eren, restaurar o canal e alinhar três espelhos interrompe o ciclo.',
 'jardim', [('Arco de entrada',20,76),('Biblioteca aberta',24,26),('Observatório',75,25),('Jardim das águas',76,76)],
 [section('1 · Arco: vozes emprestadas','Leia: “Uma frase sai das folhas com a sua própria voz. O caminho se bifurca entre estantes de pedra e um espelho voltado para o céu.”',
   'Naia entrega corda, ferramenta de ajuste e a pista 1. Cada jogador conta uma lembrança feliz que seu personagem aceita compartilhar; isso é opcional e não exige relato pessoal do jogador.',
   'Sabedoria ND 13 identifica que todos os ecos vêm do observatório. Falha revela o mesmo rumo, mas atrai uma raiz sentinela que bloqueia a passagem; contorná-la custa uma marca de tensão, sem combate obrigatório.',
   'As duas trilhas estão abertas. A biblioteca contém o aprendiz e a instrução; o jardim contém a causa hidráulica. Podem ser visitados em qualquer ordem.'),
  section('2 · Biblioteca: resgate entre raízes','Leia: “Eren mantém os pés sobre uma mesa. Raízes apertam a porta, enquanto uma estante repete: água, chão, céu.”',
   'Eren explica o erro e entrega a pista 2 mesmo se o grupo falhar. Uma ação e Força ND 13 afastam a raiz; Destreza ND 13 alcança o trinco pela janela. Falha causa 1d4 de dano a quem tenta, sem prender mais ninguém; outro método continua possível.',
   'Apresentar a ferramenta de Naia e pedir calma, com Carisma ND 13, silencia o eco que agita as raízes. Sucesso liberta Eren sem dano. Ajudar usa uma ação e concede vantagem, conforme o Livro IV.',
   'Eren acompanha o grupo como orientador; não resolve os testes. Se escoltado para fora, Naia cuida dele e o grupo pode prosseguir normalmente.'),
  section('3 · Águas: restaurar o fluxo','Leia: “Um fio de água desaparece sob uma roda parada. Pedras e galhos comprimem a comporta.”',
   'Remova o entulho com uma ação e Força ND 13, depois ajuste a roda com uma ação e Destreza ou Sabedoria ND 13. Cada falha avança a tensão; o teste pode ser repetido com outra abordagem. Ferramentas adequadas permitem a tentativa, sem bônus automático.',
   'Alternativa sem teste: três personagens usam suas ações na mesma rodada para segurar a roda, retirar pedras e abrir a passagem. Um grupo menor pode gastar dez minutos e duas marcas de tensão.',
   'Restaurar o fluxo encerra o crescimento das raízes, mas os ecos persistem até alinhar os espelhos. A placa sob a roda é a pista 3, recuperável sem teste.'),
  section('4 · Observatório: água, chão, céu','Leia: “Três espelhos cercam um cristal. Em cada superfície há uma imagem: uma gota, uma folha e uma estrela.”',
   'A ordem é gota voltada ao canal, folha ao arco de entrada, estrela ao cristal central. Com as pistas, cada ajuste custa uma ação e dispensa teste. Sem as pistas, Sabedoria ND 16 descobre um ajuste; falha avança o relógio e permite buscar a biblioteca.',
   'Antes de restaurar o fluxo, a máquina desfaz o primeiro ajuste. Deixe isso visível e explique que falta água; não consuma todas as ações do grupo em tentativas inúteis.',
   'Se quebrarem um espelho ou atacarem o cristal, desperte 2 raízes sentinelas e 1 guardião de pedra. Para 3 jogadores use só 1 raiz; para 5 use 3. Alinhar o último espelho encerra a luta imediatamente. Desligar a máquina com duas ações e Força ND 16 também encerra o perigo, mas perde o arquivo de ecos.'),
  section('Relógio de tensão · 6 marcas','Marque uma vez ao entrar em cada novo local e nas falhas indicadas; no máximo uma marca extra por rodada.',
   '3: trilhas ganham raízes e passam a terreno difícil. 5: espelhos repetem frases, mas as pistas continuam legíveis. 6: a máquina fecha o arco com raízes; ainda é possível terminar a missão e reabrir a saída, ou sair pela trilha do riacho com movimento pela metade.',
   'Restaurar o canal remove o terreno difícil. Não aumente atributos dos inimigos com o relógio. Naia ajuda na retirada, sem solucionar o observatório pelo grupo.')],
 [npc('Naia','Guardiã do jardim','Paciente, reconhece erros e pede que preservem as memórias.','Vida 18; Defesa 12; testes de natureza +5; ação Ajudar; não acompanha o combate.'),
  npc('Eren','Aprendiz arrependido','Assume a responsabilidade e explica qualquer pista esquecida.','Vida 12; Defesa 11; testes de mecanismos +3; sem ataque; movimento 6 m.'),
  npc('Raiz sentinela','Defesa do observatório','Só reage à máquina; para quando o cristal se apaga.','Vida 18; Defesa 12; ataque +5, ramo 1d6+2, alcance 1,5 m; movimento 3 m; testes +2. Sem imobilização adicional.'),
  npc('Guardião de pedra','Vigia antigo','Protege o cristal e não persegue fora do observatório.','Vida 32; Defesa 14; ataque +6, golpe 1d8+3, alcance 1,5 m; movimento 6 m; testes +4. Sem resistências especiais.')],
 [('Bilhete de Naia','Não lutem contra uma voz. Sigam o fluxo: toda lembrança precisa de um caminho de volta.','Entrada, entregue por Naia.'),
  ('Página do aprendiz','Primeiro água, depois chão, por último céu. A gota procura o canal; a folha, a entrada; a estrela, o coração de cristal.','Biblioteca, com Eren.'),
  ('Placa da comporta','Sem corrente de água, os espelhos retornam à posição de repouso. Abra o canal antes de alinhar.','Jardim, sob a roda.')],
 'Jardim restaurado: Naia oferece abrigo, provisões para sete dias e uma cópia do mapa dos caminhos élficos, sem bônus numérico automático. Máquina desligada à força: todos sobrevivem, mas os ecos antigos são perdidos; Naia pede ajuda para registrar novas histórias. Se Eren não foi resgatado, Naia o procura e a relação com o grupo fica abalada. Gancho: uma voz recuperada menciona um farol que acende sem vigia.'))

kits.append(kit('farol-mares','O farol das marés','Costa dos reinos humanos','Níveis 5–6',
 'Evacuar um farol isolado e impedir que um sinal falso atraia navios aos recifes.',
 'Uma lanterna pisca três vezes no nevoeiro. No cais, a barqueira Lia aponta para o farol: “A luz deveria avisar dos recifes. Hoje ela chama os navios para cima deles. Ainda há gente lá dentro.” A maré já cobre o primeiro degrau.',
 'O antigo vigia Otávio tentou girar a lente para chamar socorro durante uma pane. O freio quebrou e o sinal aponta para os recifes. A contrabandista Mira tomou o armazém para guardar carga, mas também ficou presa pela maré. Ela possui a peça do freio, retirada para reparar seu guincho. Todos podem ser salvos por cooperação; não existe vilão que precise morrer.',
 'farol',[('Cais de resgate',20,77),('Armazém',25,26),('Mecanismo do farol',75,25),('Gruta da maré',75,77)],
 [section('1 · Cais: um plano antes da subida','Leia: “O barco bate contra pedras. Uma corda estala, e a luz do farol varre o mar na direção errada.”',
   'Lia entrega a pista 1 e mantém o barco pronto. O grupo escolhe salvar o vigia, corrigir o sinal ou negociar uma evacuação; as três tarefas se conectam, sem ordem obrigatória.',
   'Prender a embarcação exige Destreza ND 13 ou duas ações de dois personagens usando a corda disponível, sem teste. Falha custa uma marca de maré; Lia conserva o barco, mas ele sai e retorna dez minutos depois.',
   'O cais e os caminhos de pedra são seguros enquanto não forem inundados. Cair em água junto à borda exige uma ação e Força ND 13 para subir, ou ação de um aliado com corda sem teste. Falha causa 1d4 de dano de impacto e mantém a pessoa junto à borda; não há morte automática.'),
  section('2 · Armazém: negociar a peça','Leia: “Mira empilha caixas acima da linha úmida na parede. No guincho, uma roda de bronze traz o mesmo símbolo do farol.”',
   'Mira troca a roda pela promessa de lugar no barco para sua equipe. Aceitar garante a peça sem teste e a pista 2. Carisma ND 16 também a convence a entregar a carga irregular às autoridades; falha mantém apenas o acordo de resgate.',
   'Sabedoria ND 13 encontra uma segunda corda e uma prancha útil para a gruta. Falha encontra ambas, mas a busca avança a maré. Pistas essenciais não exigem teste.',
   'Se o grupo atacar, use 2 marinheiros e 1 capataz; para 3 jogadores retire um marinheiro, para 5 acrescente um. Eles rendem-se quando o capataz cai ou quando recebem uma saída segura. Mira não luta e entrega a roda se ameaçada; registre a hostilidade futura.'),
  section('3 · Gruta: tirar Otávio da água','Leia: “O vigia se apoia num patamar seco. A escada entre vocês perdeu três degraus. Ele segura um caderno sobre a cabeça.”',
   'Uma prancha e corda resolvem a travessia em duas ações, sem teste. Sem esses materiais, Destreza ND 16 permite atravessar pela borda; falha causa 1d4 de dano e devolve o personagem ao patamar inicial.',
   'Otávio não anda depressa: escoltá-lo reduz o movimento pela metade, sem outra penalidade. Dois personagens podem carregá-lo juntos gastando suas ações para atravessar a lacuna. Ele entrega a pista 3 mesmo antes do resgate, gritando a instrução.',
   'Otávio confirma que a roda é necessária. Se o grupo já improvisou o freio, ele orienta apenas o sinal. Não exige nova rolagem para repetir uma informação obtida.'),
  section('4 · Farol: frear, alinhar, avisar','Leia: “O mecanismo gira aos solavancos. Entre cada clarão, um casco aparece no nevoeiro.”',
   'Com a roda, uma ação e Destreza ou Sabedoria ND 13 reinstalam o freio. Falha avança a maré e pode ser repetida. Duas pessoas com ferramentas e duas ações cada fazem o reparo sem teste.',
   'Depois de frear, uma ação aponta a lente para o mar aberto e outra cobre a luz para fazer três lampejos, pausa, três lampejos. As pistas revelam o procedimento; executá-lo corretamente dispensa teste e afasta o navio.',
   'Sem roda, Força ND 16 trava o eixo por uma rodada enquanto um aliado sinaliza. Falha causa 1d6 de dano a quem segura; permite outra tentativa ou buscar a peça. Alternativa: apagar o farol com uma ação e sinalizar com a lanterna do cais, gastando duas ações; salva o navio, mas deixa o farol sem funcionamento.'),
  section('Relógio de maré · 6 marcas','Avance ao entrar num novo local e nas falhas indicadas; no máximo uma marca adicional por rodada.',
   '3: cais e gruta tornam-se terreno difícil. 5: o barco só encosta junto à escada do farol. 6: o navio atinge um banco de areia e precisa de reboque; ninguém morre automaticamente. O grupo pode terminar o sinal e organizar o resgate, mas a carga se perde.',
   'Corrigir o sinal evita o encalhe, porém a maré continua subindo. Lia retorna pelo lado do farol; há espaço para todos em duas viagens. Na segunda, os personagens podem ajudar a transportar Otávio. Não exija um novo combate para encerrar.')],
 [npc('Lia','Barqueira','Põe vidas antes da carga; explica que haverá duas viagens.','Vida 20; Defesa 12; testes de navegação +5; movimento 6 m; ação Ajudar.'),
  npc('Otávio','Vigia ferido','Conhece o sinal e admite ter provocado a pane ao pedir ajuda.','Vida atual 5 de 16; Defesa 10; movimento 3 m; testes do farol +4; não luta.'),
  npc('Mira','Dona da carga irregular','Negocia proteção para sua equipe antes de qualquer lucro.','Vida 18; Defesa 12; testes sociais +4; foge ou se rende; não combate.'),
  npc('Marinheiro','Defensor do armazém','Quer sair vivo; aceita um acordo em qualquer rodada.','Vida 24; Defesa 13; ataque +6, bastão 1d6+3, alcance 1,5 m; movimento 6 m; testes +3.'),
  npc('Capataz','Responsável pela equipe','Protege os marinheiros, não luta até a morte.','Vida 38; Defesa 15; ataque +7, maça 1d8+3, alcance 1,5 m; movimento 6 m; testes +4.')],
 [('Código costeiro','Três lampejos, pausa, três lampejos: recifes à frente, afastar para mar aberto. Luz contínua aponta o canal seguro.','Cais, com Lia.'),
  ('Inventário do guincho','Roda de bronze emprestada do freio do farol. Devolver antes de acender a lente.','Armazém, com Mira.'),
  ('Caderno do vigia','Reinstalar o freio. Virar a lente para o mar aberto. Avisar com três lampejos, pausa, três lampejos. Se não houver freio, apagar a lente e usar a lanterna do cais.','Gruta, com Otávio.')],
 'Sinal corrigido e pessoas salvas: a vila oferece abrigo, provisões para uma semana e passagem futura num barco costeiro para o grupo. Se o navio encalhou, a recompensa é apenas abrigo e a amizade dos resgatados; a próxima missão pode ser recuperar a carga. Mira cumpre o acordo de resgate, mas a decisão de denunciá-la cabe ao grupo e às autoridades locais. Otávio pede ajuda para formar novos vigias. Gancho: a carga contém uma carta sobre espelhos de um jardim élfico.'))

for i,k in enumerate(kits):
    k['minPlan']='contador' if i==0 else 'mestre' if i<3 else 'deus'

import runpy
runpy.run_path(str(Path(__file__).with_name('expand-session-kits.py')))['expand'](kits,section,npc)

p=Path('assets/demo/studio.json')
data=json.loads(p.read_text(encoding='utf-8'))
data['kits']=kits
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Wrote five session kits with two illustrated boards and six scenes each.')
